### PR TITLE
fixed username displaying

### PR DESCRIPTION
**Pull request by martyalicante**

### CODE REVIEW

**Comment by Schamper** [comment]
What is wrong with it?

**Comment by martyalicante** [comment]
Wont display name on last 0.7
Maybe they removed {name} and now only works with {username}

**Comment by Schamper** [comment]
https://github.com/Schamper/nodebb-plugin-cards/blob/master/public/js/main.js#L75

It should default to `fullname` and otherwise use `username`. What does it display? Just empty text?

**Comment by martyalicante** [comment]
its says account/profile instead of the username

**Comment by Schamper** [comment]
Can you add a screenshot of what's actually wrong with it?

**Pull request closed without merging**
